## Numpy Session
### Numerical Python
##### Learn more
In this you are going to learn about arrays, ndarrays

* np.array
* np.shape
* np.arange
* np.linspace
* np.reshape

In [ ]:
INDEXING

In [1]:
import numpy as np

In [2]:
arr1=np.arange(0,16)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
arr1[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [4]:
arr1[6:9]

array([6, 7, 8])

In [5]:
a1=arr1.reshape(4,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
a1[1:3,0:3]

array([[ 4,  5,  6],
       [ 8,  9, 10]])

In [9]:
a1[0:4,0].reshape(4,1)

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [13]:
a1[2:4,0:4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
a1[2:4,0:4].reshape(4,2)  #here we want

array([[ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

## Vectorization


In [19]:
a1=np.arange(0,12,2)
a1

array([ 0,  2,  4,  6,  8, 10])

In [20]:
a1*2

array([ 0,  4,  8, 12, 16, 20])

In [21]:
a1/2

array([0., 1., 2., 3., 4., 5.])

### linspace(start_index,end_index,element)

In [1]:
import numpy as np

In [2]:
arr1=np.arange(0,16)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
a=np.linspace(1,10,50)
print(a)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [6]:
a=np.linspace(1,10,50,dtype="int") #evenly create 50 elements within 1 to 10
print(a)

[ 1  1  1  1  1  1  2  2  2  2  2  3  3  3  3  3  3  4  4  4  4  4  5  5
  5  5  5  5  6  6  6  6  6  7  7  7  7  7  7  8  8  8  8  8  9  9  9  9
  9 10]


In [7]:
a=np.linspace(1,10,50,dtype="float")
print(a)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


### np.ones, np.zeroes and np.eye

In [8]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
b=np.ones((3,4))
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
c=np.eye((3))
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Aggregate functions in Numpy min,max,mean,stdev

In [13]:
data=np.array([12,45,98,100,50])
mean1=np.mean(data)
print(mean1)

61.0


In [14]:
min_val=np.min(data)
max_val=np.max(data)
stdev=np.std(data)
sum1=np.sum(data)
print(min_val)
print(max_val)
print(stdev)
print(sum1)

12
100
33.668976818430345
305


##   78 80 90 70 45     mean of 1 row
##   30 24 50 68 53     mean of 2 row
##   90 92 87 95 99     mean of 3 row

In [23]:
a=np.array([[78,80,90,70,45],[30,24,50,68,53],[90,92,87,95,99]])
arr1=a.reshape((3,5))
arr2=arr1.mean(axis=1)
print(arr2)

[72.6 45.  92.6]


In [21]:
a=np.array([[78,80,90,70,45],[30,24,50,68,53],[90,92,87,95,99]])
mean=0
for i in a:
    mean=np.mean((i))
    print(mean)

72.6
45.0
92.6


## np.where: conditional just like if
## syntax: np.where(condition,value_if_true,value_if_false)

In [26]:
marks=np.array([78,90,89,90,88,30,24,34])
morethan50=np.where(marks>50,"Good","Work Hard")
print(morethan50)
print(type(morethan50))

['Good' 'Good' 'Good' 'Good' 'Good' 'Work Hard' 'Work Hard' 'Work Hard']
<class 'numpy.ndarray'>


In [28]:
marks=np.array([78,90,89,90,88,-30,24,34,-10])
#you have to replace negative marks with 0
negativemark=np.where(marks<0,0,marks)
print(negativemark)

[78 90 89 90 88  0 24 34  0]


In [3]:
##dealing with duplicate values
import numpy as np
colors=np.array(['red','blue','black','red','red','red'])
unique_colors=np.unique(colors)
print(unique_colors)


['black' 'blue' 'red']


#  dealing with missing values np.nan

In [6]:
price=np.array([45.60,46.80,56.70,np.nan,np.nan,45.89])
p_mean=np.nanmean(price)
print(p_mean)
final_price=np.where(np.isnan(price),p_mean,price)
print(final_price)

48.7475
[45.6    46.8    56.7    48.7475 48.7475 45.89  ]


In [7]:
price=np.array([45,98,54,np.nan,np.nan,np.nan,654])
p_mean=np.nanmean(price)
print(p_mean)
fina

212.75


# Joining Arrays
using vstack,hstack,row_stack,column_stack

In [13]:
a1=np.arange(0,16).reshape(4,4)
a2=np.arange(16,32).reshape(4,4)
merged_array=np.vstack((a1,a2))#it takes only argument so we have to pass tuple
print(merged_array)
merged_array1=np.hstack((a1,a2))
print(merged_array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 0  1  2  3 16 17 18 19]
 [ 4  5  6  7 20 21 22 23]
 [ 8  9 10 11 24 25 26 27]
 [12 13 14 15 28 29 30 31]]


In [19]:
#create one dimentional
a1=np.arange(0,16).reshape(4,4)
a2=np.arange(16,32).reshape(4,4)
a3=np.arange(32,48).reshape(4,4)
merged_array=np.vstack((a1,a2,a3))
print(merged_array)
merged_array2=np.hstack((a1,a2,a3))
print(merged_array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]
[[ 0  1  2  3 16 17 18 19 32 33 34 35]
 [ 4  5  6  7 20 21 22 23 36 37 38 39]
 [ 8  9 10 11 24 25 26 27 40 41 42 43]
 [12 13 14 15 28 29 30 31 44 45 46 47]]


In [18]:
# row stack and column stack
a1=np.arange(0,8)
a2=np.arange(8,16)
a3=np.array([89,90,91,92,92,100,101,12])
m1=np.row_stack((a1,a2,a3))
m2=np.column_stack((a1,a2,a3))
print(m1)
print(m2)

[[  0   1   2   3   4   5   6   7]
 [  8   9  10  11  12  13  14  15]
 [ 89  90  91  92  92 100 101  12]]
[[  0   8  89]
 [  1   9  90]
 [  2  10  91]
 [  3  11  92]
 [  4  12  92]
 [  5  13 100]
 [  6  14 101]
 [  7  15  12]]


C:\Users\Vikash Singh\AppData\Local\Temp\ipykernel_10896\2660711190.py:5: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  m1=np.row_stack((a1,a2,a3))


# spliting dataset

In [26]:
(s1,s2)=np.hsplit(merged_array,2)
print(s1)
print(s2)
(s1,s2)=np.vsplit(merged_array,2)
print(s1)
print(s2)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]
 [20 21]
 [24 25]
 [28 29]
 [32 33]
 [36 37]
 [40 41]
 [44 45]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]
 [22 23]
 [26 27]
 [30 31]
 [34 35]
 [38 39]
 [42 43]
 [46 47]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]
