In [2]:
import numpy as np

In [5]:
ls=[1,2,3,4,5]
print(ls)

[1, 2, 3, 4, 5]


In [11]:
#in python list we can only store 1D array while in numpy array we can store multi dimensional array
print("1D array")
a=np.array([1,2,3,4,5])
print(a)
#----------------------------------------------------------

print("2D array")
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)
#-----------------------------

print("3D array")
c=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(c)

1D array
[1 2 3 4 5]
2D array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3D array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [12]:
type(a)

numpy.ndarray

In [13]:
#   size=tells about no. of elements in that array
print(a.size)
print(b.size)
print(c.size)

5
10
15


In [15]:
#  shape=(rows,column)

print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [16]:
#   dtype=type of data present in the array

print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


In [17]:
d=np.array([[1,2,3,4.6,5],[6,7,8,9,48.5]])
print(d.dtype)

float64


In [18]:
d.transpose()

array([[ 1. ,  6. ],
       [ 2. ,  7. ],
       [ 3. ,  8. ],
       [ 4.6,  9. ],
       [ 5. , 48.5]])

In [20]:
#   np.empty((rows,cols),dtype)

np.empty((4,4),dtype=int)

array([[23925768161198147, 32370111954616435, 30118273485242460,
         9007645938876513],
       [28992395054481491, 29555070129143912, 29273895802044528,
        31525592535793775],
       [29555310648557682, 28147905699577964, 32932988893659237,
        29273792722501740],
       [31244220638625897, 32369819898151026, 32651548277080177,
        27303583844991077]])